// Generated by https://quicktype.io
import 'package:flutter/cupertino.dart';

class Peliculas {
  List<Pelicula> items = new List();
  Peliculas();

  Peliculas.fromJsonList(List<dynamic> jsonList) {
    if (jsonList != null)
      for (var item in jsonList) {
        final pelicula = new Pelicula.fromJsonMap(item);
        items.add(pelicula);
      }
  }
}

class Pelicula {
  String uniqueId;

  double popularity;
  bool adult;
  String backdropPath;
  List<int> genreIds;
  String originalLanguage;
  String originalTitle;
  String posterPath;
  int id;
  bool video;
  double voteAverage;
  int voteCount;
  String overview;
  String releaseDate;
  String title;

  Pelicula({
    this.popularity,
    this.adult,
    this.backdropPath,
    this.genreIds,
    this.originalLanguage,
    this.originalTitle,
    this.posterPath,
    this.id,
    this.video,
    this.voteAverage,
    this.voteCount,
    this.overview,
    this.releaseDate,
    this.title,
  });

  Pelicula.fromJsonMap(Map<String, dynamic> json) {
    popularity = json['popularity'] / 1;
    adult = json['adult'];
    backdropPath = json['backdrop_path'];
    genreIds = json['genre_ids'].cast<int>();
    originalLanguage = json['original_language'];
    originalTitle = json['original_title'];
    posterPath = json['poster_path'];
    id = json['id'];
    video = json['video'];
    voteAverage = json['vote_average'] / 1;
    voteCount = json['vote_count'];
    overview = json['overview'];
    releaseDate = json['release_date'];
    title = json['title'];
  }

  getPosterImg() {
    if (posterPath == null) {
      return 'https://farm5.staticflickr.com/4363/36346283311_74018f6e7d_o.png';
    }
    return 'https://image.tmdb.org/t/p/w500/$posterPath';
  }

  getBackgroundImg() {
    if (backdropPath == null) {
      return 'https://farm5.staticflickr.com/4363/36346283311_74018f6e7d_o.png';
    }
    return 'https://image.tmdb.org/t/p/w500/$backdropPath';
  }
}
